# security
security:
  user:
    name: admin
    password: admin

spring:
    datasource:
        name: h5perf
        url: jdbc:mysql://localhost:3306/lightsword?autoReconnect=true&useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: com.easy.springboot.mybatispagehelperfreemarker.model
    configuration:
        # 开启mybatis开启数据库字段自动映射驼峰命名规则java属性
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/sqlmap/*.xml
