package com.easy.springboot.mybatispagehelperfreemarker.mapper;

import com.easy.springboot.mybatispagehelperfreemarker.model.HttpApi;

public interface HttpApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_api
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_api
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int insert(HttpApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_api
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int insertSelective(HttpApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_api
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    HttpApi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_api
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int updateByPrimaryKeySelective(HttpApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_api
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int updateByPrimaryKey(HttpApi record);
}