package com.easy.springboot.mybatispagehelperfreemarker.mapper;

import com.easy.springboot.mybatispagehelperfreemarker.model.HttpReport;

public interface HttpReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_report
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_report
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int insert(HttpReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_report
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int insertSelective(HttpReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_report
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    HttpReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_report
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int updateByPrimaryKeySelective(HttpReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_report
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    int updateByPrimaryKey(HttpReport record);
}