package com.easy.springboot.mybatispagehelperfreemarker.model;

import java.util.Date;

public class HttpReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_report.id
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_report.fail
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    private Integer fail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_report.http_suite_id
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    private Integer httpSuiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_report.http_suite_name
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    private String httpSuiteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_report.pass
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    private Integer pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_report.time
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_report.rate
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    private Double rate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_report.id
     *
     * @return the value of http_report.id
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_report.id
     *
     * @param id the value for http_report.id
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_report.fail
     *
     * @return the value of http_report.fail
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public Integer getFail() {
        return fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_report.fail
     *
     * @param fail the value for http_report.fail
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public void setFail(Integer fail) {
        this.fail = fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_report.http_suite_id
     *
     * @return the value of http_report.http_suite_id
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public Integer getHttpSuiteId() {
        return httpSuiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_report.http_suite_id
     *
     * @param httpSuiteId the value for http_report.http_suite_id
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public void setHttpSuiteId(Integer httpSuiteId) {
        this.httpSuiteId = httpSuiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_report.http_suite_name
     *
     * @return the value of http_report.http_suite_name
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public String getHttpSuiteName() {
        return httpSuiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_report.http_suite_name
     *
     * @param httpSuiteName the value for http_report.http_suite_name
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public void setHttpSuiteName(String httpSuiteName) {
        this.httpSuiteName = httpSuiteName == null ? null : httpSuiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_report.pass
     *
     * @return the value of http_report.pass
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public Integer getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_report.pass
     *
     * @param pass the value for http_report.pass
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public void setPass(Integer pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_report.time
     *
     * @return the value of http_report.time
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_report.time
     *
     * @param time the value for http_report.time
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_report.rate
     *
     * @return the value of http_report.rate
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_report.rate
     *
     * @param rate the value for http_report.rate
     *
     * @mbg.generated Fri Aug 11 13:25:36 CST 2017
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }
}