package com.easy.springboot.mybatispagehelperfreemarker.model;

import java.util.Date;

public class HttpApi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.actual_output
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private String actualOutput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.expect_output
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private String expectOutput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.gmt_create
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.gmt_modify
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.http_suite_id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private Integer httpSuiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.method
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.name
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.owner
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.param_json_str
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private String paramJsonStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.run_times
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private Integer runTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.state
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_api.url
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.id
     *
     * @return the value of http_api.id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.id
     *
     * @param id the value for http_api.id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.actual_output
     *
     * @return the value of http_api.actual_output
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public String getActualOutput() {
        return actualOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.actual_output
     *
     * @param actualOutput the value for http_api.actual_output
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setActualOutput(String actualOutput) {
        this.actualOutput = actualOutput == null ? null : actualOutput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.expect_output
     *
     * @return the value of http_api.expect_output
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public String getExpectOutput() {
        return expectOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.expect_output
     *
     * @param expectOutput the value for http_api.expect_output
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setExpectOutput(String expectOutput) {
        this.expectOutput = expectOutput == null ? null : expectOutput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.gmt_create
     *
     * @return the value of http_api.gmt_create
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.gmt_create
     *
     * @param gmtCreate the value for http_api.gmt_create
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.gmt_modify
     *
     * @return the value of http_api.gmt_modify
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.gmt_modify
     *
     * @param gmtModify the value for http_api.gmt_modify
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.http_suite_id
     *
     * @return the value of http_api.http_suite_id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public Integer getHttpSuiteId() {
        return httpSuiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.http_suite_id
     *
     * @param httpSuiteId the value for http_api.http_suite_id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setHttpSuiteId(Integer httpSuiteId) {
        this.httpSuiteId = httpSuiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.method
     *
     * @return the value of http_api.method
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.method
     *
     * @param method the value for http_api.method
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.name
     *
     * @return the value of http_api.name
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.name
     *
     * @param name the value for http_api.name
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.owner
     *
     * @return the value of http_api.owner
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.owner
     *
     * @param owner the value for http_api.owner
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.param_json_str
     *
     * @return the value of http_api.param_json_str
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public String getParamJsonStr() {
        return paramJsonStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.param_json_str
     *
     * @param paramJsonStr the value for http_api.param_json_str
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setParamJsonStr(String paramJsonStr) {
        this.paramJsonStr = paramJsonStr == null ? null : paramJsonStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.run_times
     *
     * @return the value of http_api.run_times
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public Integer getRunTimes() {
        return runTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.run_times
     *
     * @param runTimes the value for http_api.run_times
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setRunTimes(Integer runTimes) {
        this.runTimes = runTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.state
     *
     * @return the value of http_api.state
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.state
     *
     * @param state the value for http_api.state
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_api.url
     *
     * @return the value of http_api.url
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_api.url
     *
     * @param url the value for http_api.url
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}