package com.easy.springboot.mybatispagehelperfreemarker.model;

public class HttpSuite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_suite.id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_suite.name
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_suite.id
     *
     * @return the value of http_suite.id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_suite.id
     *
     * @param id the value for http_suite.id
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_suite.name
     *
     * @return the value of http_suite.name
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_suite.name
     *
     * @param name the value for http_suite.name
     *
     * @mbg.generated Fri Aug 11 12:53:13 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}